server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ms-estadisticas
  datasource:
    url: jdbc:noop
    driver-class-name: org.h2.Driver
  autoconfigure:
    exclude: 
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

logging:
  level:
    root: ${LOG_LEVEL_ROOT}
    'co.edu.unicauca.estadistica.api': ${LOG_LEVEL_API}
  file:
    name: ${LOG_FILE_NAME}
    max-size: ${LOG_FILE_MAX_SIZE}
    max-history: ${LOG_FILE_MAX_HISTORY}
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  default-produces-media-type: application/json

info:
  app:
    title: Microservicio Estadísticas - Evaluación Docente
    description: API para estadísticas sobre evaluaciones por fuente y actividad
    version: 1.0.0
